In [ ]:
# RNN basics

In [4]:
import tensorflow as tf
import numpy as np

hidden_size = 2
cell = tf.keras.layers.LSTMCell(hidden_size)

x_data = np.array([[[1,0,0,0]]], dtype=np.float32)
lstm_layer = tf.keras.layers.RNN(cell)
outputs = lstm_layer(x_data)
print(outputs)

tf.Tensor([[-0.11690753  0.07944884]], shape=(1, 2), dtype=float32)


In [11]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

hidden_size = 2
cell = tf.keras.layers.LSTMCell(hidden_size)
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
print(x_data.shape)
print(x_data)
lstm_layer = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = lstm_layer(x_data)
print(outputs)

(1, 5, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
tf.Tensor(
[[[-0.02432331 -0.07986384]
  [ 0.01014244 -0.00163616]
  [-0.0807649  -0.04257509]
  [-0.13832843 -0.07828099]
  [-0.16634329  0.02335155]]], shape=(1, 5, 2), dtype=float32)


In [12]:
hidden_size = 2
cell = tf.keras.layers.LSTMCell(hidden_size)
x_data = np.array([[h,e,l,l,o],
                   [e,o,l,l,l],
                   [l,l,e,e,l]], dtype=np.float32)
print(x_data.shape)
print(x_data)
lstm_layer = tf.keras.layers.RNN(cell, return_sequences=True)
outputs = lstm_layer(x_data)
print(outputs)

(3, 5, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]]
tf.Tensor(
[[[-0.04915144  0.1541966 ]
  [-0.14793703  0.08674915]
  [-0.06229985  0.0745756 ]
  [ 0.03633004  0.07324812]
  [-0.07178465  0.13286923]]

 [[-0.10874154 -0.05740786]
  [-0.18627107  0.06609683]
  [-0.06943312  0.0781995 ]
  [ 0.03039405  0.07585375]
  [ 0.11451358  0.07247307]]

 [[ 0.08627946  0.02613318]
  [ 0.15708333  0.04018814]
  [-0.01850189 -0.02431619]
  [-0.12052272 -0.07431175]
  [-0.0365148  -0.00885959]]], shape=(3, 5, 2), dtype=float32)
