In [ ]:
# logistic classification

In [1]:
import tensorflow as tf

x_data = [[1., 2.],
          [2., 3.],
          [3., 1.],
          [4., 3.],
          [5., 3.],
          [6., 2.]]
y_data = [[0], [0], [0], [1], [1], [1]]

W = tf.Variable(tf.random.normal([2, 1]), name="weight")
b = tf.Variable(tf.random.normal([1]), name="bias")

optimizer = tf.optimizers.SGD(learning_rate=0.01)

def compute_cost(X, Y):
    hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
    Y = tf.convert_to_tensor(Y, dtype=tf.float32)
    cost = -tf.reduce_mean(Y * tf.math.log(hypothesis) + (1 - Y) * tf.math.log(1 - hypothesis))
    return hypothesis, cost

def train_step(X, Y):
    with tf.GradientTape() as tape:
        hypothesis, cost = compute_cost(X, Y)
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return hypothesis, cost

for step in range(10001):
    hy_val, cost_val = train_step(x_data, y_data)
    predicted = tf.cast(hy_val > 0.5, dtype=tf.float32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y_data), dtype=tf.float32))
    if step % 200 == 0:
        print(step, "Cost: ", cost_val.numpy(), "\nPredicted:\n", predicted.numpy(), "\nAccuracy: ", accuracy.numpy())


0 Cost:  3.1657608 
Predicted:
 [[1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.16666667
200 Cost:  1.1159761 
Predicted:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  0.33333334
400 Cost:  0.72858256 
Predicted:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.5
600 Cost:  0.56535125 
Predicted:
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.6666667
800 Cost:  0.49543676 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1000 Cost:  0.45825836 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1200 Cost:  0.43380594 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1400 Cost:  0.41507304 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1600 Cost:  0.39929616 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
1800 Cost:  0.3852663 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.8333333
2000 Cost:  0.37240782 
Predicted:
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.