In [ ]:
# softmax classification

In [ ]:
x_data = [[1., 2., 1., 1.],
          [2., 1., 3., 2.],
          [3., 1., 3., 4.],
          [4., 1., 5., 5.],
          [1., 7., 5., 5.],
          [1., 2., 5., 6.],
          [1., 6., 6., 6.],
          [1., 7., 7., 7.]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

nb_classes = 3
W = tf.Variable(tf.random.normal([4, nb_classes]), name="weight")
b = tf.Variable(tf.random.normal([nb_classes]), name="bias")

optimizer = tf.optimizers.SGD(learning_rate=0.1)

def compute_cost(X, Y=[0, 0, 0]):
    hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
    Y = tf.convert_to_tensor(Y, dtype=tf.float32)
    cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis), axis=1))
    return hypothesis, cost

def train_step(X, Y):
    with tf.GradientTape() as tape:
        _, cost = compute_cost(X, Y)
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return cost

for step in range(10001):
    cost_val = train_step(x_data, y_data)
    if step % 200 == 0:
        print(step, "Cost: ", cost_val.numpy())


In [ ]:
predictions = compute_cost(X=[[1., 11., 7., 9.]])[0].numpy()
print(tf.argmax(predictions, axis=1).numpy())

all = compute_cost(X=[[1., 11., 7., 9.],
                      [1., 3., 4., 3.],
                      [1., 1., 0., 1.]])[0].numpy()
print(tf.argmax(all, axis=1).numpy())

[1]
[1 0 2]


In [ ]:
# 메소드 추천
logits = tf.matmul(x_data, W) + b
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_data)
cost = tf.reduce_mean(cost_i)
print(cost)

Y = [[0], [1], [2], [3], [4], [5], [6]]
nb_classes = 7
Y_one_hot = tf.one_hot(Y, nb_classes)
print(Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print(Y_one_hot)

tf.Tensor(0.03948453, shape=(), dtype=float32)
tf.Tensor(
[[[1. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 0. 0. 1.]]], shape=(7, 1, 7), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]], shape=(7, 7), dtype=float32)


In [ ]:
x_data = [[1., 2., 1., 1.],
          [2., 1., 3., 2.],
          [3., 1., 3., 4.],
          [4., 1., 5., 5.],
          [1., 7., 5., 5.],
          [1., 2., 5., 6.],
          [1., 6., 6., 6.],
          [1., 7., 7., 7.]]
y_data = [[2], [2], [2], [1], [1], [1], [0], [0]]

nb_classes = 3

Y_one_hot = tf.one_hot(y_data, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

W = tf.Variable(tf.random.normal([4, nb_classes]), name="weight")
b = tf.Variable(tf.random.normal([nb_classes]), name="bias")

optimizer = tf.optimizers.SGD(learning_rate=0.1)

def compute_cost(X, Y):
    logits = tf.matmul(X, W) + b
    hypothesis = tf.nn.softmax(logits)
    cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y)
    cost = tf.reduce_mean(cost_i)
    return hypothesis, cost

def train_step(X, Y):
    with tf.GradientTape() as tape:
        hypothesis, cost = compute_cost(X, Y)
    gradients  = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    return hypothesis, cost

for step in range(2000):
    hypothesis, cost_val = train_step(x_data, Y_one_hot)
    prediction = tf.argmax(hypothesis, 1)
    correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    if step % 100 == 0:
        print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, cost_val.numpy(), accuracy))

Step:     0	Loss: 10.043	Acc: 37.50%
Step:   100	Loss: 0.661	Acc: 75.00%
Step:   200	Loss: 0.578	Acc: 75.00%
Step:   300	Loss: 0.520	Acc: 75.00%
Step:   400	Loss: 0.469	Acc: 87.50%
Step:   500	Loss: 0.421	Acc: 87.50%
Step:   600	Loss: 0.375	Acc: 87.50%
Step:   700	Loss: 0.329	Acc: 87.50%
Step:   800	Loss: 0.285	Acc: 87.50%
Step:   900	Loss: 0.250	Acc: 100.00%
Step:  1000	Loss: 0.236	Acc: 100.00%
Step:  1100	Loss: 0.224	Acc: 100.00%
Step:  1200	Loss: 0.214	Acc: 100.00%
Step:  1300	Loss: 0.204	Acc: 100.00%
Step:  1400	Loss: 0.196	Acc: 100.00%
Step:  1500	Loss: 0.188	Acc: 100.00%
Step:  1600	Loss: 0.180	Acc: 100.00%
Step:  1700	Loss: 0.173	Acc: 100.00%
Step:  1800	Loss: 0.167	Acc: 100.00%
Step:  1900	Loss: 0.161	Acc: 100.00%


In [ ]:
import numpy as np

hypothesis, _ = compute_cost(x_data, Y_one_hot)
prediction = tf.argmax(hypothesis, 1)

for p, y in zip(prediction, np.array(y_data).flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 2 True Y: 2
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
